### ISSUE TITLE
Tratamento de erro na execução do Buildout

### ISSUE THREAD

**Issue by deyvsonaguiar** [odoo-brazil/odoo-brazil-buildout#10]
No meio da minha instalação dá esse erro, podem me ajudar a discernir qual seria a solução?

Segue: 

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/opt/odoo10/src/anybox.recipe.odoo/anybox/recipe/odoo/base.py", line 1114, in install
    self.install_requirements()
  File "/opt/odoo10/src/anybox.recipe.odoo/anybox/recipe/odoo/base.py", line 557, in install_requirements
    eggs_recipe.install()
  File "/opt/odoo10/eggs/zc.recipe.egg-2.0.4-py2.7.egg/zc/recipe/egg/egg.py", line 193, in install
    reqs, ws = self.working_set()
  File "/opt/odoo10/eggs/zc.recipe.egg-2.0.4-py2.7.egg/zc/recipe/egg/egg.py", line 82, in working_set
    allow_hosts=self.allow_hosts,
  File "/opt/odoo10/eggs/zc.recipe.egg-2.0.4-py2.7.egg/zc/recipe/egg/egg.py", line 135, in _working_set
    allow_hosts=allow_hosts)
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 665, in install
    for dist in self._get_dist(requirement, ws):
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/opt/odoo10/local/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack

**Comment by mileo** [comment]
Comece o buildout com o comando:

virtualenv -p python3 .  # ou python 2 para o Odoo < 11
bin/pip install -U zc.buildout==2.8.0 pip
bin/buildout

**Comment by mileo** [comment]
Outra coisa são as versões do setuptools e do buildout no cfg

`
[versions]
# Avoid Buildout infinite subprocess recursion:
# https://github.com/buildout/buildout/issues/312
setuptools = 
pybrasil =
geraldo =
pysped =
py3o.template =
py3o.formats =
#pyboleto =
pyusb=1.0.0b2

appdirs=1.4.2
packaging=16.8
pyparsing=2.1.10
six=1.11.0
zc.buildout=2.8.0`
